### ISSUE TITLE
Split specific-module styles into categories

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-Shared-iOS#1]
In order to enhance mantainability, let's split specific-module styles into categories, and place them in the right pod(s). 

I.e.: WPStyleGuide+Stats, WPStyleGuide+Notifications.

**Comment by nheagy** [comment]
This seems to have been done, at least `WPStyleGuide+Stats` appears to have been removed. If I'm wrong, feel free to open a new issue in https://github.com/wordpress-mobile/WordPress-iOS
