### ISSUE TITLE
New color palette: block quotes

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-Shared-iOS#15]
Background color of block quotes in comments should be white, not gray:

![](https://i.cloudup.com/3h-8_TZW0P.png)

Background color of block quotes on a white background should be #E8F0F5 [rgb(232, 240, 245)], not gray:

![](https://i.cloudup.com/K6kfNxL4IX.png)

**Comment by nheagy** [comment]
This seems to have been fixed in wordpress-mobile/WordPress-iOS#2406
