### ISSUE TITLE
New color palette: cell tap

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-Shared-iOS#17]
It would be nice to customize this tap color on table view cells:

![](https://i.cloudup.com/ShlHvfAs4Y.png)

It looks like only the background color is changed, and there isn't any kind of opacity overlay going on, so I think #d2dee6 [rgb(210, 222, 230)] would be the best color for this.

**Comment by nheagy** [comment]
This will be addressed in wordpress-mobile/WordPress-iOS#6591
