### ISSUE TITLE
Design: update colors and variables

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-Shared-iOS#47]
We finally have a nice color system in WordPress.com for the grays and the naming. I'd like to update the style guide to reflect those changes.

Here are the latest colors: https://wordpress.com/design-handbook/colors/

This will include changing the variable names to be more consistent with WordPress.com. For example, instead of `readGrey`, `whisperGrey`, etc, it would be `grayLight`, `grayDark`, `grayLighten20`, etc.

**Comment by drw158** [comment]
Here is a conversion chart for updating to the new variables:

```
baseLighterBlue = wordPressBlue
baseDarkerBlue = wordPressBlue
newKidOnTheBlockBlue = mediumBlue
midnightBlue = darkBlue

bigEddieGrey = darkGrey
littleEddieGrey = darkGrey
whisperGrey = darkenGrey20
allTAllShadeGrey = grey
readGrey =  lightenGrey20
itsEverywhereGrey = lightenGrey30
darkAsNightGrey = darkBlue
textFieldPlaceholderGrey = grey

validationErrorRed = alertRed
nuxFormText = darkGrey
nuxFormPlaceholderText = grey
notificationsLightGrey = lightGrey
notificationsDarkGrey = lightenGrey20
```

**Comment by aerych** [comment]
@drw158 I'm gonna steal this one from ya :) I'll implement these changes as a part of the post list refresh.  I'll ping ya for a review when I have them ready.

**Comment by drw158** [comment]
Thank you!

The same Android PR is here, just for reference: https://github.com/wordpress-mobile/WordPress-Android/pull/2185
