### ISSUE TITLE
Can we integrate github markdown?

### ISSUE THREAD

**Issue by mejiamariano** [wordpress-mobile/WordPress-Shared-iOS#66]
It will be great if we add this tool.

**Comment by sendhil** [comment]
@mejiamariano what do you mean? In the editor?

**Comment by mejiamariano** [comment]
@sendhil, yes

**Comment by sendhil** [comment]
Ahhh, gotcha. While it would be neat to have that in the editor, given the editor is now WYSIWYG supporting markdown isn't a very high priority. Going to close this issue.

**Comment by bummytime** [comment]
@mejiamariano Just as a FYI, we already have this enhancement request logged here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/296. However, everything @sendhil just said is true...it just is not a priority at this time.
